---
title: "Category by Country"
format: html
editor: visual
---

```{r}

##read in database
data_base <- read_csv(here::here("data/Working_Policy_Database_1.csv")) %>% 
  janitor::clean_names() 
  
 ##select main descriptive policies 
##please note field names and update if necessary
cat_nation_df <- data_base %>% 
  select(title_of_policy, ##title of policy
         # lat, ##latitude,
         # lon, ##longitude
         # legal_status, ##denoting statutory vs. non
         policy_category, ##main category of policy (clean procurement, building codes/planning)
         policy_subcategory, 
         methodology, ##method of achieving carbon reduction
         participation, ##mandatory vs. voluntary
         location, ##specific location 
         country, ##country where policy is implemented
         jurisdiction)

##remove nas
cat_nation_df_clean <- cat_nation_df[!is.na(cat_nation_df$country), ]


policy_category_pallette <- c("Climate Commitment" = "#29af7FFF",
                          "Clean Procurement" = "#33638DFF", "Building Codes/Planning" = "#482677ff", "Training & Education" = "#fde725")
```

```{r}


```

policy_counts \<- policies %\>%

group_by(country, policy_category) %\>%

summarise(count = n(), .groups = "drop") \# Add a count column

```{r}


policies_expanded <- cat_nation_df_clean %>%
  separate_rows(policy_category, policy_subcategory, sep = ",")
# 
# cat_breakdown_bar_df <- policies_expanded %>%
#   group_by(policy_category, policy_subcategory) %>%
#   summarise(count=n())


# 
# country_primary <- cat_nation_df_clean %>% 
#   group_by(country, primary_policy_category_broad) %>% 
#   summarize(count = n()) %>% 
#   rename("category" = primary_policy_category_broad)
# 
# country_secondary <- cat_nation_df_clean %>% 
#   select(country, secondary_category_if_necessary) %>% 
#   drop_na() %>% 
#   group_by(country, secondary_category_if_necessary) %>%
#   summarize(count = n()) %>% 
#   rename("category" = secondary_category_if_necessary)
# 
# country_cat_combined <- rbind(country_primary, country_secondary)

country_cat_combined_graph_ready <- policies_expanded %>% 
    group_by(country, policy_category) %>% 
  summarise(count = n())

# policy_counts <- policies %>%
#   group_by(country, policy_category) %>%
#   summarise(count = n(), .groups = "drop")  # Add a count column
# 
stacked_cat_country <- ggplot(data=country_cat_combined_graph_ready, aes(x=country, y=total, fill=policy_category)) +
  geom_bar(stat="identity")+
  labs(x="Country", y="Number of Policies", fill="Policy Category", title="Policy Count by Country and Category")+
  scale_y_continuous(breaks=seq(0, 40, by=1))+
  scale_fill_manual(values=policy_category_pallette)+
  theme_minimal()+
  theme(axis.title = element_text(face="bold",
                                  family="inter",
                                   size=35),
        plot.title=element_text(face="bold",
                                family="inter",
                                   size=40),
        legend.title=element_text(face="bold",
                                  family="inter",
                                  size=30),
        axis.text = element_text(family="poppins",
                                 size=30),
        legend.text = element_text(family="poppins",
                                 size=30),
        legend.position="bottom")+

  coord_flip()


stacked_cat_country


ggsave(here::here("images/stacked_cat_country.png"), plot = stacked_cat_country, width = 10, height = 4, dpi = 320)
```
